create table "public"."children" (
    "id" integer generated by default as identity not null,
    "name" text not null
);


alter table "public"."children" enable row level security;

create table "public"."covid_vaccine" (
    "id" integer generated by default as identity not null,
    "name" text not null
);


alter table "public"."covid_vaccine" enable row level security;

create table "public"."ethinicities" (
    "id" integer generated by default as identity not null,
    "name" text not null
);


alter table "public"."ethinicities" enable row level security;

create table "public"."family_plans" (
    "id" integer generated by default as identity not null,
    "name" text not null
);


alter table "public"."family_plans" enable row level security;

create table "public"."genders" (
    "id" integer generated by default as identity not null,
    "name" text not null,
    "plural_name" text
);


alter table "public"."genders" enable row level security;

create table "public"."interaction_status" (
    "id" integer generated by default as identity not null,
    "status" text not null
);


alter table "public"."interaction_status" enable row level security;

create table "public"."interactions" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "updated_by" uuid not null,
    "actor_id" uuid not null,
    "target_id" uuid not null,
    "status_id" integer not null,
    "answer_id" uuid,
    "photo_id" uuid
);


alter table "public"."interactions" enable row level security;

create table "public"."pets" (
    "id" integer generated by default as identity not null,
    "name" text not null
);


alter table "public"."pets" enable row level security;

create table "public"."profile_answers" (
    "id" uuid not null default gen_random_uuid(),
    "profile_id" uuid not null,
    "prompt_id" integer not null,
    "answer_text" text not null,
    "answer_order" integer not null,
    "is_active" boolean not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."profile_answers" enable row level security;

create table "public"."profile_ethinicities" (
    "profile_id" uuid not null,
    "ethnicity_id" integer not null
);


alter table "public"."profile_ethinicities" enable row level security;

create table "public"."profile_ethnicity_preferences" (
    "profile_id" uuid not null,
    "ethnicity_id" integer not null
);


alter table "public"."profile_ethnicity_preferences" enable row level security;

create table "public"."profile_gender_preferences" (
    "profile_id" uuid not null,
    "gender_id" integer not null
);


alter table "public"."profile_gender_preferences" enable row level security;

create table "public"."profile_pets" (
    "profile_id" uuid not null,
    "pets_id" integer not null
);


alter table "public"."profile_pets" enable row level security;

create table "public"."profile_photos" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "profile_id" uuid not null,
    "photo_url" text not null,
    "photo_order" integer not null,
    "is_active" boolean not null
);


alter table "public"."profile_photos" enable row level security;

create table "public"."profile_pronouns" (
    "profile_id" uuid not null,
    "pronouns_id" integer not null
);


alter table "public"."profile_pronouns" enable row level security;

create table "public"."profiles" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "first_name" text,
    "last_name" text,
    "dob" date,
    "height" integer,
    "neighborhood" text,
    "latitude" double precision,
    "longitude" double precision,
    "children_id" integer,
    "family_plan_id" integer,
    "covid_vaccine_id" integer,
    "zodiac_signs_id" integer,
    "gender_id" integer,
    "sexuality_id" integer,
    "max_distance_mi" integer default 100,
    "min_age" integer default 18,
    "max_age" integer default 100,
    "phone" text
);


alter table "public"."profiles" enable row level security;

create table "public"."prompts" (
    "id" integer generated by default as identity not null,
    "question" text not null
);


alter table "public"."prompts" enable row level security;

create table "public"."pronouns" (
    "id" integer generated by default as identity not null,
    "name" text not null
);


alter table "public"."pronouns" enable row level security;

create table "public"."sexualities" (
    "id" integer generated by default as identity not null,
    "name" text not null
);


alter table "public"."sexualities" enable row level security;

create table "public"."zodiac_signs" (
    "id" integer generated by default as identity not null,
    "name" text not null
);


alter table "public"."zodiac_signs" enable row level security;

CREATE UNIQUE INDEX children_pkey ON public.children USING btree (id);

CREATE UNIQUE INDEX covid_vaccine_pkey ON public.covid_vaccine USING btree (id);

CREATE UNIQUE INDEX ethinicities_pkey ON public.ethinicities USING btree (id);

CREATE UNIQUE INDEX family_plans_pkey ON public.family_plans USING btree (id);

CREATE UNIQUE INDEX genders_pkey ON public.genders USING btree (id);

CREATE UNIQUE INDEX interaction_status_pkey ON public.interaction_status USING btree (id);

CREATE UNIQUE INDEX interactions_pkey ON public.interactions USING btree (id);

CREATE UNIQUE INDEX pets_pkey ON public.pets USING btree (id);

CREATE UNIQUE INDEX profile_answers_pkey ON public.profile_answers USING btree (id);

CREATE UNIQUE INDEX profile_ethinicities_pkey ON public.profile_ethinicities USING btree (profile_id, ethnicity_id);

CREATE UNIQUE INDEX profile_ethnicity_preferences_pkey ON public.profile_ethnicity_preferences USING btree (profile_id, ethnicity_id);

CREATE UNIQUE INDEX profile_gender_preferences_pkey ON public.profile_gender_preferences USING btree (profile_id, gender_id);

CREATE UNIQUE INDEX profile_pets_pkey ON public.profile_pets USING btree (profile_id, pets_id);

CREATE UNIQUE INDEX profile_photos_pkey ON public.profile_photos USING btree (id);

CREATE UNIQUE INDEX profile_pronouns_pkey ON public.profile_pronouns USING btree (profile_id, pronouns_id);

CREATE UNIQUE INDEX profiles_phone_key ON public.profiles USING btree (phone);

CREATE UNIQUE INDEX profiles_pkey ON public.profiles USING btree (id);

CREATE UNIQUE INDEX prompts_pkey ON public.prompts USING btree (id);

CREATE UNIQUE INDEX pronouns_pkey ON public.pronouns USING btree (id);

CREATE UNIQUE INDEX sexualities_pkey ON public.sexualities USING btree (id);

CREATE UNIQUE INDEX zodiac_signs_pkey ON public.zodiac_signs USING btree (id);

alter table "public"."children" add constraint "children_pkey" PRIMARY KEY using index "children_pkey";

alter table "public"."covid_vaccine" add constraint "covid_vaccine_pkey" PRIMARY KEY using index "covid_vaccine_pkey";

alter table "public"."ethinicities" add constraint "ethinicities_pkey" PRIMARY KEY using index "ethinicities_pkey";

alter table "public"."family_plans" add constraint "family_plans_pkey" PRIMARY KEY using index "family_plans_pkey";

alter table "public"."genders" add constraint "genders_pkey" PRIMARY KEY using index "genders_pkey";

alter table "public"."interaction_status" add constraint "interaction_status_pkey" PRIMARY KEY using index "interaction_status_pkey";

alter table "public"."interactions" add constraint "interactions_pkey" PRIMARY KEY using index "interactions_pkey";

alter table "public"."pets" add constraint "pets_pkey" PRIMARY KEY using index "pets_pkey";

alter table "public"."profile_answers" add constraint "profile_answers_pkey" PRIMARY KEY using index "profile_answers_pkey";

alter table "public"."profile_ethinicities" add constraint "profile_ethinicities_pkey" PRIMARY KEY using index "profile_ethinicities_pkey";

alter table "public"."profile_ethnicity_preferences" add constraint "profile_ethnicity_preferences_pkey" PRIMARY KEY using index "profile_ethnicity_preferences_pkey";

alter table "public"."profile_gender_preferences" add constraint "profile_gender_preferences_pkey" PRIMARY KEY using index "profile_gender_preferences_pkey";

alter table "public"."profile_pets" add constraint "profile_pets_pkey" PRIMARY KEY using index "profile_pets_pkey";

alter table "public"."profile_photos" add constraint "profile_photos_pkey" PRIMARY KEY using index "profile_photos_pkey";

alter table "public"."profile_pronouns" add constraint "profile_pronouns_pkey" PRIMARY KEY using index "profile_pronouns_pkey";

alter table "public"."profiles" add constraint "profiles_pkey" PRIMARY KEY using index "profiles_pkey";

alter table "public"."prompts" add constraint "prompts_pkey" PRIMARY KEY using index "prompts_pkey";

alter table "public"."pronouns" add constraint "pronouns_pkey" PRIMARY KEY using index "pronouns_pkey";

alter table "public"."sexualities" add constraint "sexualities_pkey" PRIMARY KEY using index "sexualities_pkey";

alter table "public"."zodiac_signs" add constraint "zodiac_signs_pkey" PRIMARY KEY using index "zodiac_signs_pkey";

alter table "public"."interactions" add constraint "interactions_actor_id_fkey" FOREIGN KEY (actor_id) REFERENCES profiles(id) not valid;

alter table "public"."interactions" validate constraint "interactions_actor_id_fkey";

alter table "public"."interactions" add constraint "interactions_answer_id_fkey" FOREIGN KEY (answer_id) REFERENCES profile_answers(id) not valid;

alter table "public"."interactions" validate constraint "interactions_answer_id_fkey";

alter table "public"."interactions" add constraint "interactions_photo_id_fkey" FOREIGN KEY (photo_id) REFERENCES profile_photos(id) not valid;

alter table "public"."interactions" validate constraint "interactions_photo_id_fkey";

alter table "public"."interactions" add constraint "interactions_status_id_fkey" FOREIGN KEY (status_id) REFERENCES interaction_status(id) not valid;

alter table "public"."interactions" validate constraint "interactions_status_id_fkey";

alter table "public"."interactions" add constraint "interactions_target_id_fkey" FOREIGN KEY (target_id) REFERENCES profiles(id) not valid;

alter table "public"."interactions" validate constraint "interactions_target_id_fkey";

alter table "public"."interactions" add constraint "interactions_updated_by_fkey" FOREIGN KEY (updated_by) REFERENCES profiles(id) not valid;

alter table "public"."interactions" validate constraint "interactions_updated_by_fkey";

alter table "public"."profile_answers" add constraint "profile_answers_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE not valid;

alter table "public"."profile_answers" validate constraint "profile_answers_profile_id_fkey";

alter table "public"."profile_answers" add constraint "profile_answers_prompt_id_fkey" FOREIGN KEY (prompt_id) REFERENCES prompts(id) not valid;

alter table "public"."profile_answers" validate constraint "profile_answers_prompt_id_fkey";

alter table "public"."profile_ethinicities" add constraint "profile_ethinicities_ethnicity_id_fkey" FOREIGN KEY (ethnicity_id) REFERENCES ethinicities(id) not valid;

alter table "public"."profile_ethinicities" validate constraint "profile_ethinicities_ethnicity_id_fkey";

alter table "public"."profile_ethinicities" add constraint "profile_ethinicities_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE not valid;

alter table "public"."profile_ethinicities" validate constraint "profile_ethinicities_profile_id_fkey";

alter table "public"."profile_ethnicity_preferences" add constraint "profile_ethnicity_preferences_ethnicity_id_fkey" FOREIGN KEY (ethnicity_id) REFERENCES ethinicities(id) not valid;

alter table "public"."profile_ethnicity_preferences" validate constraint "profile_ethnicity_preferences_ethnicity_id_fkey";

alter table "public"."profile_ethnicity_preferences" add constraint "profile_ethnicity_preferences_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE not valid;

alter table "public"."profile_ethnicity_preferences" validate constraint "profile_ethnicity_preferences_profile_id_fkey";

alter table "public"."profile_gender_preferences" add constraint "profile_gender_preferences_gender_id_fkey" FOREIGN KEY (gender_id) REFERENCES genders(id) ON DELETE CASCADE not valid;

alter table "public"."profile_gender_preferences" validate constraint "profile_gender_preferences_gender_id_fkey";

alter table "public"."profile_gender_preferences" add constraint "profile_gender_preferences_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES profiles(id) not valid;

alter table "public"."profile_gender_preferences" validate constraint "profile_gender_preferences_profile_id_fkey";

alter table "public"."profile_pets" add constraint "profile_pets_pets_id_fkey" FOREIGN KEY (pets_id) REFERENCES pets(id) ON DELETE CASCADE not valid;

alter table "public"."profile_pets" validate constraint "profile_pets_pets_id_fkey";

alter table "public"."profile_pets" add constraint "profile_pets_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES profiles(id) not valid;

alter table "public"."profile_pets" validate constraint "profile_pets_profile_id_fkey";

alter table "public"."profile_photos" add constraint "profile_photos_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE not valid;

alter table "public"."profile_photos" validate constraint "profile_photos_profile_id_fkey";

alter table "public"."profile_pronouns" add constraint "profile_pronouns_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES profiles(id) not valid;

alter table "public"."profile_pronouns" validate constraint "profile_pronouns_profile_id_fkey";

alter table "public"."profile_pronouns" add constraint "profile_pronouns_pronouns_id_fkey" FOREIGN KEY (pronouns_id) REFERENCES pronouns(id) ON DELETE CASCADE not valid;

alter table "public"."profile_pronouns" validate constraint "profile_pronouns_pronouns_id_fkey";

alter table "public"."profiles" add constraint "profiles_children_id_fkey" FOREIGN KEY (children_id) REFERENCES children(id) not valid;

alter table "public"."profiles" validate constraint "profiles_children_id_fkey";

alter table "public"."profiles" add constraint "profiles_covid_vaccine_id_fkey" FOREIGN KEY (covid_vaccine_id) REFERENCES covid_vaccine(id) not valid;

alter table "public"."profiles" validate constraint "profiles_covid_vaccine_id_fkey";

alter table "public"."profiles" add constraint "profiles_family_plan_id_fkey" FOREIGN KEY (family_plan_id) REFERENCES family_plans(id) not valid;

alter table "public"."profiles" validate constraint "profiles_family_plan_id_fkey";

alter table "public"."profiles" add constraint "profiles_gender_id_fkey" FOREIGN KEY (gender_id) REFERENCES genders(id) not valid;

alter table "public"."profiles" validate constraint "profiles_gender_id_fkey";

alter table "public"."profiles" add constraint "profiles_phone_key" UNIQUE using index "profiles_phone_key";

alter table "public"."profiles" add constraint "profiles_sexuality_id_fkey" FOREIGN KEY (sexuality_id) REFERENCES sexualities(id) not valid;

alter table "public"."profiles" validate constraint "profiles_sexuality_id_fkey";

alter table "public"."profiles" add constraint "profiles_zodiac_signs_id_fkey" FOREIGN KEY (zodiac_signs_id) REFERENCES zodiac_signs(id) not valid;

alter table "public"."profiles" validate constraint "profiles_zodiac_signs_id_fkey";

grant delete on table "public"."children" to "anon";

grant insert on table "public"."children" to "anon";

grant references on table "public"."children" to "anon";

grant select on table "public"."children" to "anon";

grant trigger on table "public"."children" to "anon";

grant truncate on table "public"."children" to "anon";

grant update on table "public"."children" to "anon";

grant delete on table "public"."children" to "authenticated";

grant insert on table "public"."children" to "authenticated";

grant references on table "public"."children" to "authenticated";

grant select on table "public"."children" to "authenticated";

grant trigger on table "public"."children" to "authenticated";

grant truncate on table "public"."children" to "authenticated";

grant update on table "public"."children" to "authenticated";

grant delete on table "public"."children" to "service_role";

grant insert on table "public"."children" to "service_role";

grant references on table "public"."children" to "service_role";

grant select on table "public"."children" to "service_role";

grant trigger on table "public"."children" to "service_role";

grant truncate on table "public"."children" to "service_role";

grant update on table "public"."children" to "service_role";

grant delete on table "public"."covid_vaccine" to "anon";

grant insert on table "public"."covid_vaccine" to "anon";

grant references on table "public"."covid_vaccine" to "anon";

grant select on table "public"."covid_vaccine" to "anon";

grant trigger on table "public"."covid_vaccine" to "anon";

grant truncate on table "public"."covid_vaccine" to "anon";

grant update on table "public"."covid_vaccine" to "anon";

grant delete on table "public"."covid_vaccine" to "authenticated";

grant insert on table "public"."covid_vaccine" to "authenticated";

grant references on table "public"."covid_vaccine" to "authenticated";

grant select on table "public"."covid_vaccine" to "authenticated";

grant trigger on table "public"."covid_vaccine" to "authenticated";

grant truncate on table "public"."covid_vaccine" to "authenticated";

grant update on table "public"."covid_vaccine" to "authenticated";

grant delete on table "public"."covid_vaccine" to "service_role";

grant insert on table "public"."covid_vaccine" to "service_role";

grant references on table "public"."covid_vaccine" to "service_role";

grant select on table "public"."covid_vaccine" to "service_role";

grant trigger on table "public"."covid_vaccine" to "service_role";

grant truncate on table "public"."covid_vaccine" to "service_role";

grant update on table "public"."covid_vaccine" to "service_role";

grant delete on table "public"."ethinicities" to "anon";

grant insert on table "public"."ethinicities" to "anon";

grant references on table "public"."ethinicities" to "anon";

grant select on table "public"."ethinicities" to "anon";

grant trigger on table "public"."ethinicities" to "anon";

grant truncate on table "public"."ethinicities" to "anon";

grant update on table "public"."ethinicities" to "anon";

grant delete on table "public"."ethinicities" to "authenticated";

grant insert on table "public"."ethinicities" to "authenticated";

grant references on table "public"."ethinicities" to "authenticated";

grant select on table "public"."ethinicities" to "authenticated";

grant trigger on table "public"."ethinicities" to "authenticated";

grant truncate on table "public"."ethinicities" to "authenticated";

grant update on table "public"."ethinicities" to "authenticated";

grant delete on table "public"."ethinicities" to "service_role";

grant insert on table "public"."ethinicities" to "service_role";

grant references on table "public"."ethinicities" to "service_role";

grant select on table "public"."ethinicities" to "service_role";

grant trigger on table "public"."ethinicities" to "service_role";

grant truncate on table "public"."ethinicities" to "service_role";

grant update on table "public"."ethinicities" to "service_role";

grant delete on table "public"."family_plans" to "anon";

grant insert on table "public"."family_plans" to "anon";

grant references on table "public"."family_plans" to "anon";

grant select on table "public"."family_plans" to "anon";

grant trigger on table "public"."family_plans" to "anon";

grant truncate on table "public"."family_plans" to "anon";

grant update on table "public"."family_plans" to "anon";

grant delete on table "public"."family_plans" to "authenticated";

grant insert on table "public"."family_plans" to "authenticated";

grant references on table "public"."family_plans" to "authenticated";

grant select on table "public"."family_plans" to "authenticated";

grant trigger on table "public"."family_plans" to "authenticated";

grant truncate on table "public"."family_plans" to "authenticated";

grant update on table "public"."family_plans" to "authenticated";

grant delete on table "public"."family_plans" to "service_role";

grant insert on table "public"."family_plans" to "service_role";

grant references on table "public"."family_plans" to "service_role";

grant select on table "public"."family_plans" to "service_role";

grant trigger on table "public"."family_plans" to "service_role";

grant truncate on table "public"."family_plans" to "service_role";

grant update on table "public"."family_plans" to "service_role";

grant delete on table "public"."genders" to "anon";

grant insert on table "public"."genders" to "anon";

grant references on table "public"."genders" to "anon";

grant select on table "public"."genders" to "anon";

grant trigger on table "public"."genders" to "anon";

grant truncate on table "public"."genders" to "anon";

grant update on table "public"."genders" to "anon";

grant delete on table "public"."genders" to "authenticated";

grant insert on table "public"."genders" to "authenticated";

grant references on table "public"."genders" to "authenticated";

grant select on table "public"."genders" to "authenticated";

grant trigger on table "public"."genders" to "authenticated";

grant truncate on table "public"."genders" to "authenticated";

grant update on table "public"."genders" to "authenticated";

grant delete on table "public"."genders" to "service_role";

grant insert on table "public"."genders" to "service_role";

grant references on table "public"."genders" to "service_role";

grant select on table "public"."genders" to "service_role";

grant trigger on table "public"."genders" to "service_role";

grant truncate on table "public"."genders" to "service_role";

grant update on table "public"."genders" to "service_role";

grant delete on table "public"."interaction_status" to "anon";

grant insert on table "public"."interaction_status" to "anon";

grant references on table "public"."interaction_status" to "anon";

grant select on table "public"."interaction_status" to "anon";

grant trigger on table "public"."interaction_status" to "anon";

grant truncate on table "public"."interaction_status" to "anon";

grant update on table "public"."interaction_status" to "anon";

grant delete on table "public"."interaction_status" to "authenticated";

grant insert on table "public"."interaction_status" to "authenticated";

grant references on table "public"."interaction_status" to "authenticated";

grant select on table "public"."interaction_status" to "authenticated";

grant trigger on table "public"."interaction_status" to "authenticated";

grant truncate on table "public"."interaction_status" to "authenticated";

grant update on table "public"."interaction_status" to "authenticated";

grant delete on table "public"."interaction_status" to "service_role";

grant insert on table "public"."interaction_status" to "service_role";

grant references on table "public"."interaction_status" to "service_role";

grant select on table "public"."interaction_status" to "service_role";

grant trigger on table "public"."interaction_status" to "service_role";

grant truncate on table "public"."interaction_status" to "service_role";

grant update on table "public"."interaction_status" to "service_role";

grant delete on table "public"."interactions" to "anon";

grant insert on table "public"."interactions" to "anon";

grant references on table "public"."interactions" to "anon";

grant select on table "public"."interactions" to "anon";

grant trigger on table "public"."interactions" to "anon";

grant truncate on table "public"."interactions" to "anon";

grant update on table "public"."interactions" to "anon";

grant delete on table "public"."interactions" to "authenticated";

grant insert on table "public"."interactions" to "authenticated";

grant references on table "public"."interactions" to "authenticated";

grant select on table "public"."interactions" to "authenticated";

grant trigger on table "public"."interactions" to "authenticated";

grant truncate on table "public"."interactions" to "authenticated";

grant update on table "public"."interactions" to "authenticated";

grant delete on table "public"."interactions" to "service_role";

grant insert on table "public"."interactions" to "service_role";

grant references on table "public"."interactions" to "service_role";

grant select on table "public"."interactions" to "service_role";

grant trigger on table "public"."interactions" to "service_role";

grant truncate on table "public"."interactions" to "service_role";

grant update on table "public"."interactions" to "service_role";

grant delete on table "public"."pets" to "anon";

grant insert on table "public"."pets" to "anon";

grant references on table "public"."pets" to "anon";

grant select on table "public"."pets" to "anon";

grant trigger on table "public"."pets" to "anon";

grant truncate on table "public"."pets" to "anon";

grant update on table "public"."pets" to "anon";

grant delete on table "public"."pets" to "authenticated";

grant insert on table "public"."pets" to "authenticated";

grant references on table "public"."pets" to "authenticated";

grant select on table "public"."pets" to "authenticated";

grant trigger on table "public"."pets" to "authenticated";

grant truncate on table "public"."pets" to "authenticated";

grant update on table "public"."pets" to "authenticated";

grant delete on table "public"."pets" to "service_role";

grant insert on table "public"."pets" to "service_role";

grant references on table "public"."pets" to "service_role";

grant select on table "public"."pets" to "service_role";

grant trigger on table "public"."pets" to "service_role";

grant truncate on table "public"."pets" to "service_role";

grant update on table "public"."pets" to "service_role";

grant delete on table "public"."profile_answers" to "anon";

grant insert on table "public"."profile_answers" to "anon";

grant references on table "public"."profile_answers" to "anon";

grant select on table "public"."profile_answers" to "anon";

grant trigger on table "public"."profile_answers" to "anon";

grant truncate on table "public"."profile_answers" to "anon";

grant update on table "public"."profile_answers" to "anon";

grant delete on table "public"."profile_answers" to "authenticated";

grant insert on table "public"."profile_answers" to "authenticated";

grant references on table "public"."profile_answers" to "authenticated";

grant select on table "public"."profile_answers" to "authenticated";

grant trigger on table "public"."profile_answers" to "authenticated";

grant truncate on table "public"."profile_answers" to "authenticated";

grant update on table "public"."profile_answers" to "authenticated";

grant delete on table "public"."profile_answers" to "service_role";

grant insert on table "public"."profile_answers" to "service_role";

grant references on table "public"."profile_answers" to "service_role";

grant select on table "public"."profile_answers" to "service_role";

grant trigger on table "public"."profile_answers" to "service_role";

grant truncate on table "public"."profile_answers" to "service_role";

grant update on table "public"."profile_answers" to "service_role";

grant delete on table "public"."profile_ethinicities" to "anon";

grant insert on table "public"."profile_ethinicities" to "anon";

grant references on table "public"."profile_ethinicities" to "anon";

grant select on table "public"."profile_ethinicities" to "anon";

grant trigger on table "public"."profile_ethinicities" to "anon";

grant truncate on table "public"."profile_ethinicities" to "anon";

grant update on table "public"."profile_ethinicities" to "anon";

grant delete on table "public"."profile_ethinicities" to "authenticated";

grant insert on table "public"."profile_ethinicities" to "authenticated";

grant references on table "public"."profile_ethinicities" to "authenticated";

grant select on table "public"."profile_ethinicities" to "authenticated";

grant trigger on table "public"."profile_ethinicities" to "authenticated";

grant truncate on table "public"."profile_ethinicities" to "authenticated";

grant update on table "public"."profile_ethinicities" to "authenticated";

grant delete on table "public"."profile_ethinicities" to "service_role";

grant insert on table "public"."profile_ethinicities" to "service_role";

grant references on table "public"."profile_ethinicities" to "service_role";

grant select on table "public"."profile_ethinicities" to "service_role";

grant trigger on table "public"."profile_ethinicities" to "service_role";

grant truncate on table "public"."profile_ethinicities" to "service_role";

grant update on table "public"."profile_ethinicities" to "service_role";

grant delete on table "public"."profile_ethnicity_preferences" to "anon";

grant insert on table "public"."profile_ethnicity_preferences" to "anon";

grant references on table "public"."profile_ethnicity_preferences" to "anon";

grant select on table "public"."profile_ethnicity_preferences" to "anon";

grant trigger on table "public"."profile_ethnicity_preferences" to "anon";

grant truncate on table "public"."profile_ethnicity_preferences" to "anon";

grant update on table "public"."profile_ethnicity_preferences" to "anon";

grant delete on table "public"."profile_ethnicity_preferences" to "authenticated";

grant insert on table "public"."profile_ethnicity_preferences" to "authenticated";

grant references on table "public"."profile_ethnicity_preferences" to "authenticated";

grant select on table "public"."profile_ethnicity_preferences" to "authenticated";

grant trigger on table "public"."profile_ethnicity_preferences" to "authenticated";

grant truncate on table "public"."profile_ethnicity_preferences" to "authenticated";

grant update on table "public"."profile_ethnicity_preferences" to "authenticated";

grant delete on table "public"."profile_ethnicity_preferences" to "service_role";

grant insert on table "public"."profile_ethnicity_preferences" to "service_role";

grant references on table "public"."profile_ethnicity_preferences" to "service_role";

grant select on table "public"."profile_ethnicity_preferences" to "service_role";

grant trigger on table "public"."profile_ethnicity_preferences" to "service_role";

grant truncate on table "public"."profile_ethnicity_preferences" to "service_role";

grant update on table "public"."profile_ethnicity_preferences" to "service_role";

grant delete on table "public"."profile_gender_preferences" to "anon";

grant insert on table "public"."profile_gender_preferences" to "anon";

grant references on table "public"."profile_gender_preferences" to "anon";

grant select on table "public"."profile_gender_preferences" to "anon";

grant trigger on table "public"."profile_gender_preferences" to "anon";

grant truncate on table "public"."profile_gender_preferences" to "anon";

grant update on table "public"."profile_gender_preferences" to "anon";

grant delete on table "public"."profile_gender_preferences" to "authenticated";

grant insert on table "public"."profile_gender_preferences" to "authenticated";

grant references on table "public"."profile_gender_preferences" to "authenticated";

grant select on table "public"."profile_gender_preferences" to "authenticated";

grant trigger on table "public"."profile_gender_preferences" to "authenticated";

grant truncate on table "public"."profile_gender_preferences" to "authenticated";

grant update on table "public"."profile_gender_preferences" to "authenticated";

grant delete on table "public"."profile_gender_preferences" to "service_role";

grant insert on table "public"."profile_gender_preferences" to "service_role";

grant references on table "public"."profile_gender_preferences" to "service_role";

grant select on table "public"."profile_gender_preferences" to "service_role";

grant trigger on table "public"."profile_gender_preferences" to "service_role";

grant truncate on table "public"."profile_gender_preferences" to "service_role";

grant update on table "public"."profile_gender_preferences" to "service_role";

grant delete on table "public"."profile_pets" to "anon";

grant insert on table "public"."profile_pets" to "anon";

grant references on table "public"."profile_pets" to "anon";

grant select on table "public"."profile_pets" to "anon";

grant trigger on table "public"."profile_pets" to "anon";

grant truncate on table "public"."profile_pets" to "anon";

grant update on table "public"."profile_pets" to "anon";

grant delete on table "public"."profile_pets" to "authenticated";

grant insert on table "public"."profile_pets" to "authenticated";

grant references on table "public"."profile_pets" to "authenticated";

grant select on table "public"."profile_pets" to "authenticated";

grant trigger on table "public"."profile_pets" to "authenticated";

grant truncate on table "public"."profile_pets" to "authenticated";

grant update on table "public"."profile_pets" to "authenticated";

grant delete on table "public"."profile_pets" to "service_role";

grant insert on table "public"."profile_pets" to "service_role";

grant references on table "public"."profile_pets" to "service_role";

grant select on table "public"."profile_pets" to "service_role";

grant trigger on table "public"."profile_pets" to "service_role";

grant truncate on table "public"."profile_pets" to "service_role";

grant update on table "public"."profile_pets" to "service_role";

grant delete on table "public"."profile_photos" to "anon";

grant insert on table "public"."profile_photos" to "anon";

grant references on table "public"."profile_photos" to "anon";

grant select on table "public"."profile_photos" to "anon";

grant trigger on table "public"."profile_photos" to "anon";

grant truncate on table "public"."profile_photos" to "anon";

grant update on table "public"."profile_photos" to "anon";

grant delete on table "public"."profile_photos" to "authenticated";

grant insert on table "public"."profile_photos" to "authenticated";

grant references on table "public"."profile_photos" to "authenticated";

grant select on table "public"."profile_photos" to "authenticated";

grant trigger on table "public"."profile_photos" to "authenticated";

grant truncate on table "public"."profile_photos" to "authenticated";

grant update on table "public"."profile_photos" to "authenticated";

grant delete on table "public"."profile_photos" to "service_role";

grant insert on table "public"."profile_photos" to "service_role";

grant references on table "public"."profile_photos" to "service_role";

grant select on table "public"."profile_photos" to "service_role";

grant trigger on table "public"."profile_photos" to "service_role";

grant truncate on table "public"."profile_photos" to "service_role";

grant update on table "public"."profile_photos" to "service_role";

grant delete on table "public"."profile_pronouns" to "anon";

grant insert on table "public"."profile_pronouns" to "anon";

grant references on table "public"."profile_pronouns" to "anon";

grant select on table "public"."profile_pronouns" to "anon";

grant trigger on table "public"."profile_pronouns" to "anon";

grant truncate on table "public"."profile_pronouns" to "anon";

grant update on table "public"."profile_pronouns" to "anon";

grant delete on table "public"."profile_pronouns" to "authenticated";

grant insert on table "public"."profile_pronouns" to "authenticated";

grant references on table "public"."profile_pronouns" to "authenticated";

grant select on table "public"."profile_pronouns" to "authenticated";

grant trigger on table "public"."profile_pronouns" to "authenticated";

grant truncate on table "public"."profile_pronouns" to "authenticated";

grant update on table "public"."profile_pronouns" to "authenticated";

grant delete on table "public"."profile_pronouns" to "service_role";

grant insert on table "public"."profile_pronouns" to "service_role";

grant references on table "public"."profile_pronouns" to "service_role";

grant select on table "public"."profile_pronouns" to "service_role";

grant trigger on table "public"."profile_pronouns" to "service_role";

grant truncate on table "public"."profile_pronouns" to "service_role";

grant update on table "public"."profile_pronouns" to "service_role";

grant delete on table "public"."profiles" to "anon";

grant insert on table "public"."profiles" to "anon";

grant references on table "public"."profiles" to "anon";

grant select on table "public"."profiles" to "anon";

grant trigger on table "public"."profiles" to "anon";

grant truncate on table "public"."profiles" to "anon";

grant update on table "public"."profiles" to "anon";

grant delete on table "public"."profiles" to "authenticated";

grant insert on table "public"."profiles" to "authenticated";

grant references on table "public"."profiles" to "authenticated";

grant select on table "public"."profiles" to "authenticated";

grant trigger on table "public"."profiles" to "authenticated";

grant truncate on table "public"."profiles" to "authenticated";

grant update on table "public"."profiles" to "authenticated";

grant delete on table "public"."profiles" to "service_role";

grant insert on table "public"."profiles" to "service_role";

grant references on table "public"."profiles" to "service_role";

grant select on table "public"."profiles" to "service_role";

grant trigger on table "public"."profiles" to "service_role";

grant truncate on table "public"."profiles" to "service_role";

grant update on table "public"."profiles" to "service_role";

grant delete on table "public"."prompts" to "anon";

grant insert on table "public"."prompts" to "anon";

grant references on table "public"."prompts" to "anon";

grant select on table "public"."prompts" to "anon";

grant trigger on table "public"."prompts" to "anon";

grant truncate on table "public"."prompts" to "anon";

grant update on table "public"."prompts" to "anon";

grant delete on table "public"."prompts" to "authenticated";

grant insert on table "public"."prompts" to "authenticated";

grant references on table "public"."prompts" to "authenticated";

grant select on table "public"."prompts" to "authenticated";

grant trigger on table "public"."prompts" to "authenticated";

grant truncate on table "public"."prompts" to "authenticated";

grant update on table "public"."prompts" to "authenticated";

grant delete on table "public"."prompts" to "service_role";

grant insert on table "public"."prompts" to "service_role";

grant references on table "public"."prompts" to "service_role";

grant select on table "public"."prompts" to "service_role";

grant trigger on table "public"."prompts" to "service_role";

grant truncate on table "public"."prompts" to "service_role";

grant update on table "public"."prompts" to "service_role";

grant delete on table "public"."pronouns" to "anon";

grant insert on table "public"."pronouns" to "anon";

grant references on table "public"."pronouns" to "anon";

grant select on table "public"."pronouns" to "anon";

grant trigger on table "public"."pronouns" to "anon";

grant truncate on table "public"."pronouns" to "anon";

grant update on table "public"."pronouns" to "anon";

grant delete on table "public"."pronouns" to "authenticated";

grant insert on table "public"."pronouns" to "authenticated";

grant references on table "public"."pronouns" to "authenticated";

grant select on table "public"."pronouns" to "authenticated";

grant trigger on table "public"."pronouns" to "authenticated";

grant truncate on table "public"."pronouns" to "authenticated";

grant update on table "public"."pronouns" to "authenticated";

grant delete on table "public"."pronouns" to "service_role";

grant insert on table "public"."pronouns" to "service_role";

grant references on table "public"."pronouns" to "service_role";

grant select on table "public"."pronouns" to "service_role";

grant trigger on table "public"."pronouns" to "service_role";

grant truncate on table "public"."pronouns" to "service_role";

grant update on table "public"."pronouns" to "service_role";

grant delete on table "public"."sexualities" to "anon";

grant insert on table "public"."sexualities" to "anon";

grant references on table "public"."sexualities" to "anon";

grant select on table "public"."sexualities" to "anon";

grant trigger on table "public"."sexualities" to "anon";

grant truncate on table "public"."sexualities" to "anon";

grant update on table "public"."sexualities" to "anon";

grant delete on table "public"."sexualities" to "authenticated";

grant insert on table "public"."sexualities" to "authenticated";

grant references on table "public"."sexualities" to "authenticated";

grant select on table "public"."sexualities" to "authenticated";

grant trigger on table "public"."sexualities" to "authenticated";

grant truncate on table "public"."sexualities" to "authenticated";

grant update on table "public"."sexualities" to "authenticated";

grant delete on table "public"."sexualities" to "service_role";

grant insert on table "public"."sexualities" to "service_role";

grant references on table "public"."sexualities" to "service_role";

grant select on table "public"."sexualities" to "service_role";

grant trigger on table "public"."sexualities" to "service_role";

grant truncate on table "public"."sexualities" to "service_role";

grant update on table "public"."sexualities" to "service_role";

grant delete on table "public"."zodiac_signs" to "anon";

grant insert on table "public"."zodiac_signs" to "anon";

grant references on table "public"."zodiac_signs" to "anon";

grant select on table "public"."zodiac_signs" to "anon";

grant trigger on table "public"."zodiac_signs" to "anon";

grant truncate on table "public"."zodiac_signs" to "anon";

grant update on table "public"."zodiac_signs" to "anon";

grant delete on table "public"."zodiac_signs" to "authenticated";

grant insert on table "public"."zodiac_signs" to "authenticated";

grant references on table "public"."zodiac_signs" to "authenticated";

grant select on table "public"."zodiac_signs" to "authenticated";

grant trigger on table "public"."zodiac_signs" to "authenticated";

grant truncate on table "public"."zodiac_signs" to "authenticated";

grant update on table "public"."zodiac_signs" to "authenticated";

grant delete on table "public"."zodiac_signs" to "service_role";

grant insert on table "public"."zodiac_signs" to "service_role";

grant references on table "public"."zodiac_signs" to "service_role";

grant select on table "public"."zodiac_signs" to "service_role";

grant trigger on table "public"."zodiac_signs" to "service_role";

grant truncate on table "public"."zodiac_signs" to "service_role";

grant update on table "public"."zodiac_signs" to "service_role";


